title: Autrement Saint Jean de Monts
baseURL: /
params:
  footer:
    content: '&copy; Netary. Tous droits réservés.'
    has_nav: true
    has_social: true
    has_subscribe: true
    links:
      - new_window: true
        text: Netary
        url: 'https://netary.fr'
    logo_img: /images/Copie de Autrement.png
    nav_title: Menu
    social_title: Suivez-nous
    subscribe_content: Recevez nos dernières actualités en vous abonnant à notre newsletter.
    subscribe_title: Abonnez-vous
    tagline: Développé par Netary
  header:
    has_nav: true
    logo_img: /images/logo new color.png
    title: Autrement Saint Jean de Monts
    menu:
      actions:
        - label: Contactez-nous
          url: /contact
  palette: blue
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
