title: Autrement Saint Jean de Monts
baseURL: /
params:
  footer:
    content: '&copy; Netary. Tous droits réservés.'
    has_nav: true
    has_social: true
    has_subscribe: false
    links:
      - new_window: true
        text: Netary
        url: 'https://netary.fr'
    logo_img: images/logo_alt.png
    nav_title: Menu
    social_title: Suivez-nous
    subscribe_content: Stay up to date with our latest developments.
    subscribe_title: Subscribe
    tagline: Développé par Netary
  header:
    has_nav: true
    logo_img: images/logo.png
    title: Autrement Saint Jean de Monts
    menu:
      actions:
        - label: Contactez-nous
          url: /signup
  palette: blue
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
